clickhouse:
  image: yandex/clickhouse-server
  ports:
  - "8123:8123"
  volumes:
  - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
  - "./data/clickhouse/data:/var/lib/clickhouse/data"
  - "./data/clickhouse/metadata:/var/lib/clickhouse/metadata"
clickhouse-init:
  image: yandex/clickhouse-server
  volumes:
  - "./init.sql:/init.sql"
  entrypoint: |
    bash -c '
      sleep 5
      export HOME=/var/lib/clickhouse/
      cat /init.sql | clickhouse client --host clickhouse --multiquery'
  links:
  - clickhouse
carbon-clickhouse:
  image: lomik/carbon-clickhouse:v0.9.1
  volumes:
  - "./data/carbon-clickhouse:/data/carbon-clickhouse"
  - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
  ports:
  - "2003:2003" # plain tcp
  - "2003:2003/udp" # plain udp
  - "2004:2004" # pickle
  - "2006:2006" # prometheus remote write
  links:
  - clickhouse
grafana:
  image: grafana/grafana
  ports:
  - "3000:3000"
  volumes:
  #- ./grafana/grafana.ini:/etc/grafana/grafana.ini
  - ./grafana/dashboards:/var/lib/grafana/dashboards
  - ./grafana/datasources:/etc/grafana/datasources
  - ./grafana/provisioning:/etc/grafana/provisioning
  environment:
  - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
  links:
  - clickhouse
grafana-key:
  image: python:3.6-alpine
  volumes:
  - ./grafana-key:/grafana-key
  entrypoint: |
    sh -c '
      pip install requests && python /grafana-key/get_key.py'
  links:
  - grafana

